<html>
 <head>
   <title>Node</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
     <link rel="stylesheet" href="/css/common.css" type="text/css" />
	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen,print" />
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
</head>
 <body>
 	<div class="contaner">
 		<div class="row">
 			<div class="col-xs-12">
 				<div class="col-xs-1"></div>
 				<div class="col-xs-10"><h1><a class="btn btn-primary" href="<?php echo ADMINURL;?>/Node/add">add</a></h1></div>
 				<div class="col-xs-1"></div>
 				
 			</div>
 			<div class="col-xs-12">
 				<div class="col-xs-1"></div>
 			<div class="col-xs-10">
 				    <table class="table table-hover table-bordered">
				      <thead>
				        <tr>
				          <th>#</th>
				          <th>Name</th>
				          <th>Title</th>
				          <th>Status</th>
				          <th>Remark</th>
				          <th>sort</th>
				          <th>operate</th>
				        </tr>
				      </thead>
				      <tbody>
				         <form class="form-horizontal" action="<?php echo ADMINURL;?>/Node/sorthandle" method="post">
				        	<?php
				        	 if(is_array($content)){


				        	   foreach ($content as $k => $v) {
				        	?>
				        	<tr>
                            <td scope="row"><?php echo $v['html'];?></td>
				          <td><?php echo $v['name'];?></td>
				          <td><?php echo $v['title'];?></td>
				          <td><?php echo $v['status'];?></td>
				          <td><?php echo $v['remark'];?></td>
				          <td><input type="text" class="form-control" id="name" name="pid" placeholder="name" value="<?php echo $v['sort'];?>"></td>
				          <td>
				          	 <a class="btn btn-primary" href="<?php echo ADMINURL;?>/Node/edit/id/<?php echo $v['id'];?>">update</a>
					          <a class="btn btn-primary" href="<?php echo ADMINURL;?>/Node/del/id/<?php echo $v['id'];?>">del</a>
					          <a class="btn btn-primary" href="<?php echo ADMINURL;?>/Node/add/id/<?php echo $v['id'];?>">add</a>
				         </td>
				         </tr>
				        	<?php
				        	   	# code...
				        	    }
				        	   }
				        	?>

				       </form>
				      </tbody>
				    </table>
 			</div>
 			<div class="clo-xs-1"></div>
 			</div>
 			
 		</div>
 		<div class="row">
 			<div class="col-xs-4"></div>
 			<div class="col-xs-4">
 				<input type="submit" class="btn btn-primary" placeholder="name" value="submit">                
 			</div>
 			<div class="col-xs-4"></div>
 		</div>
 	</div>

 </body>
</html>