<html>
 <head>
   <title>UserRole</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen,print" />
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
</head>
 <body>
 	<div class="contaner">
 		<div class="row">
 			<div class="col-xs-12">
 				<div class="col-xs-4"></div>
 				<div class="col-xs-4"><h1>AddUserRole</h1></div>
 				<div class="col-xs-4"><?php if(!empty($msg))echo $msg;?></div>
 			</div>
 			<div class="col-xs-12">
 				
 				<div class="col-xs-3"></div>
	 			<div class="col-xs-6">
	 			<form class="form-horizontal" action="<?php echo ADMINURL.'/User/addroleH'?>" method="post">

	 				
                                        <div class="form-group">
                                           <label for="name" class="col-sm-2 control-label">Role</label>
				             <div class="col-sm-5">
					      <select class="form-control" name="role_id">   
					        
				        	<?php
				        	 if(is_array($content)){


				        	   foreach ($content as $v) {
				        	?>
					               
					               	  <option value="<?php echo $v['id'];?>"><?php echo $v['name'];?></option>
					              
				        	<?php
				        	    }
				        	   }
				        	?>
				             </select>
					    </div>
					  </div>
	                                <div class="form-group">
	                                  <label for="name" class="col-sm-2 control-label">User</label>
	                                  <div class="col-sm-8">
					      <input class="form-control" id="disabledInput" type="text" placeholder="" value="<?php echo $name;?>" disabled>
					    </div>
	                                  
					  </div>
					  <div class="form-group">
					    <div class="col-sm-offset-2 col-sm-10">
					    	<input type="hidden" class="form-control" name="user_id" placeholder="name" value="<?php echo $id;?>">
					      <button type="submit" class="btn btn-primary">Submit</button>
					    </div>
					  </div>
                                    </form>
	 			</div>
	 			<div class="clo-xs-3"></div>
	 			</div>
 			
 		</div>
 		<div class="row">
 			<div class="col-xs-4"></div>
 			<div class="col-xs-4">
 				<nav>
                   <ul class="pagination"><?php echo isset($page)?$page:'';?>  </ul>
                  </nav>                  
 			</div>
 			<div class="col-xs-4"></div>
 		</div>
 	</div>

 </body>
</html>