<html>
 <head>
   <title>MsgBoard</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen,print" />
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
</head>
 <body>
 	<div class="contaner">
 		<div class="row">
 			<div class="col-xs-12">
 				<div class="col-xs-4"></div>
 				<div class="col-xs-4"><h1>MsgBoard</h1></div>
 				<div class="col-xs-4"></div>
 			</div>
 			<div class="col-xs-12">
 				<div class="col-xs-1"></div>
 				<div class="col-xs-10"><h1><a class="btn btn-primary" href="<?php echo ADMINURL;?>/index/add">add</a></h1></div>
 				<div class="col-xs-1"></div>
 				
 			</div>
 			<div class="col-xs-12">
 				<div class="col-xs-1"></div>
 			<div class="col-xs-10">
 				    <table class="table table-hover table-bordered">
				      <thead>
				        <tr>
				          <th>Id</th>
				          <th>Content</th>
				          <th>Name</th>
				          <th>Send Time</th>
				          <th>operate</th>
				        </tr>
				      </thead>
				      <tbody>
				        
				        	<?php
				        	 if(is_array($content)){


				        	   foreach ($content as $k => $v) {
				        	?>
				        	<tr>
                            <td scope="row"><?php echo $v['id']?></td>
				          <td><?php echo $v['msg_content']?></td>
				          <td><?php echo $v['msg_name']?></td>
				          <td><?php echo date("Y-m-d H:i:s",$v['submit_time'])?></td>
				          <td>
				          	 <a class="btn btn-primary" href="<?php echo ADMINURL;?>/index/edit/id/<?php echo $v['id'];?>">update</a>
					          <a class="btn btn-primary" href="<?php echo ADMINURL;?>/index/del/id/<?php echo $v['id'];?>">del</a>
				         </td>
				         </tr>
				        	<?php
				        	   	# code...
				        	    }
				        	   }
				        	?>

				       
				      </tbody>
				    </table>
 			</div>
 			<div class="clo-xs-1"></div>
 			</div>
 			
 		</div>
 		<div class="row">
 			<div class="col-xs-4"></div>
 			<div class="col-xs-4">
 				<nav>
                   <ul class="pagination"><?php echo isset($page)?$page:'';?>  </ul>
                  </nav>                  
 			</div>
 			<div class="col-xs-4"></div>
 		</div>
 	</div>

 </body>
</html>