<html>
 <head>
   <title>Roles</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
     <link rel="stylesheet" href="/css/common.css" type="text/css" media="screen,print" />
	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen,print" />
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/common.js"></script>
</head>
 <body>
 	<div class="contaner">
 		<div class="row">
 			<div class="col-xs-12">
 				<div class="col-xs-1"></div>
 				<div class="col-xs-10">
 					<h3>
 						<span class="label label-primary">
 						<?php echo urldecode($name);?>
 					       </span>
 					</h3></div>
 				<div class="col-xs-1"></div>	
 			</div>
 			<div class="col-xs-12">
 				<div class="col-xs-1"></div>
 				<form class="form-horizontal" action="<?php echo ADMINURL.'/role/accesshandle'; ?>" method="post">
	 			<div class="col-xs-10">
	 			   	<?php
	 			   	    if(is_array($content)){
	 			   	    	foreach ($content as $k=> $v) {
	 			   	?>	 			   
	 			   	<div class="panel panel-default">
                                      	<h3><?php echo $v['name'];
                                              ?><input type="checkbox" name="access[]" value="<?php echo $v['id']."\"";if(in_array($v['id'], $nodes)) echo " checked = 'checked'";?>" level="1">
                                      	<?php
                                                foreach ($v['child'] as $key => $value) {
                                              ?>
                                              </h3>
                                               <div class="panel-heading"><?php echo $value['name'];?><input name="access[]" type="checkbox" value="<?php echo $value['id']."\"";if(in_array($value['id'], $nodes)) echo " checked = 'checked'";?>" level="2"></div>
						  <div class="panel-body">
						  	<ul class="nav nav-pills">
							  
						    <?php 
						      foreach ($value['child'] as $kk => $vv){
						      	?>
						      	<li><a href="#">
						      	<?php
						      	echo $vv['name'];
						      	?><input name="access[]" type="checkbox" value="<?php echo $vv['id']."\"";if(in_array($vv['id'], $nodes)) echo " checked = 'checked'";?>" level="3">
						      	</a>
						      	</li>
						      	<?php
						      }
						    ?>
						    
							</ul>	
						    
						  </div>
                                              <?php	
                                                }
                                      	?>
					  
					</div>
	 			   	<?php
	 			   	    	}
	 			   	    }
	 			   	?>
	 			   	<div class="form-group">
					    <div class="col-sm-offset-6 col-sm-6">
					    	<input type="hidden" class="form-control" id="pid" name="id" placeholder="id" value="<?php echo $id;?>">
					      <button type="submit" class="btn btn-primary">Submit</button>
					    </div>
					</div>	
	 			       </div>	
	 			   </form>
	 			<div class="clo-xs-1"></div>
 			</div>
 			
 		</div>
 		<div class="row">
 			<div class="col-xs-4"></div>
 			<div class="col-xs-4">
 				<nav>
                   <ul class="pagination"><?php echo isset($page)?$page:'';?>  </ul>
                  </nav>                  
 			</div>
 			<div class="col-xs-4"></div>
 		</div>
 	</div>

 </body>
</html>