<html>
 <head>
   <title>AddRole</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
     	<link rel="stylesheet" href="/css/common.css" type="text/css" media="screen,print" />
	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen,print" />
	<link rel="stylesheet" href="/css/site.css" type="text/css" media="screen,print" />
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
</head>
 <body>
 	<div class="contaner">
 		<div class="row">
 			<div class="col-xs-12">
 				<div class="col-xs-4"></div>
 				<div class="col-xs-4"><h1>AddRole</h1></div>
 				<div class="col-xs-4"><?php if(!empty($msg))echo $msg;?></div>
 			</div>
 			<div class="col-xs-12">
                 <form class="form-horizontal" action="<?php echo ADMINURL;?>/role/addhandle" method="post">
				  <div class="form-group">
				    <label for="name" class="col-sm-2 control-label">name</label>
				    <div class="col-sm-5">
				      <input type="text" class="form-control" id="name" name="name" placeholder="name">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="remark" class="col-sm-2 control-label">remark</label>
				    <div class="col-sm-8">
				      <input type="text" class="form-control" id="remark" name="remark" placeholder="remark">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="status" class="col-sm-2 control-label">status</label>
				    <div class="col-sm-8">
				      <input type="text" class="form-control" id="status" name="status" placeholder="status" value="1">
				      <input type="hidden" class="form-control" id="pid" name="pid" placeholder="pid" value="0">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-2 col-sm-10">
				      <button type="submit" class="btn btn-primary">Submit</button>
				    </div>
				  </div>
				</form>  
 			</div>
 		</div>
 	</div>

 </body>
</html>
