<html>
 <head>
   <title>MsgBoard</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen,print" />
	<link rel="stylesheet" href="/css/common.css" type="text/css" media="screen,print" />
	<link rel="stylesheet" href="/css/site.css" type="text/css" media="screen,print" />
	<script src="/js/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	<style type="text/css">
        .pagination li {

		    width: auto;
		}
	</style>
</head>
 <body>
 	<div class="contaner">
 		<div class="row">
 			<div class="col-xs-12">
 				<div class="col-xs-4"></div>
 				<div class="col-xs-4"><h1>MsgBoard</h1></div>
 				<div class="col-xs-4"></div>
 			</div>
 			<div class="col-xs-12">
 				<div class="col-xs-1"></div>
 				<div class="col-xs-10"><h1><a class="btn btn-primary" href="<?php echo SYSTEMURL;?>/index/index/add">add</a></h1></div>
 				<div class="col-xs-1"></div>
 				
 			</div>

 			<div class="col-xs-1"></div>
 			<div class="col-xs-10">
 				<?php
		        	   foreach ($content as $k => $v) {
		        	?>
 				<div class="panel panel-info">
				  <div class="panel-heading"><?php echo $v['msg_name']?></div>
				  <div class="panel-body">
				    <?php echo $v['msg_content']?>
				  </div>
				  <div class="panel-footer"><?php echo date("Y-m-d H:i:s",$v['submit_time'])?></div>
				</div>
				<?php
		        	   	# code...
		        	   }
		        	?>
 			</div>
 			<div class="col-xs-1"></div>

 		</div>
 		<div class="row">
 			<div class="col-xs-12">
 			<div class="col-xs-4"></div>
 			<div class="col-xs-4">
 				<nav>
                   <ul class="pagination"><?php echo $page;?>  </ul>
                  </nav>                  
 			</div>
 			<div class="col-xs-4"></div>
 			</div>

 		</div>
 	</div>

 </body>
</html>
