<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>Login</title>
	<link href="/css/bootstrap.min.css" type="text/css" rel="stylesheet">
<script	type="text/javascript" src="/js/jquery-1.11.2.js"></script>
<script	type="text/javascript" src="/js/bootstrap.min.js"></script>
<style type="text/css">
	.jumbotron .container p a{
        width: 50%;
	}
</style>
</head>
<body>
    <div class="jumbotron">
      <div class="container">
	      <div class="col-xs-3"></div>
	      <div class="col-xs-9">
	      	<p><a class="btn btn-default btn-lg" href="#" role="button">Hello, Administrator！</a></p>
	        <p><a class="btn btn-info btn-lg" href="#" role="button">YY后台管理系统，欢迎登录！</a></p>
	        <p><a class="btn btn-warning btn-lg" href="#" role="button">您的鼠标乱点，后果不堪设想！</a></p>
	        <p><a class="btn btn-danger btn-lg" href="#" role="button">数据重地，请谨慎操作！</a></p>
	      </div>
      </div>
    </div>
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="col-xs-3"></div>
				<div class="col-xs-6">
					<form class="form-horizontal" action="<?php echo ADMINURL;?>/Login/loginH" method="post">
					  <div class="form-group">
					    <label for="name" class="col-sm-2 control-label">User</label>
					    <div class="col-sm-8">
					      <input type="text" name="name" class="form-control" id="name" placeholder="user">
					    </div>
					  </div>
					  <div class="form-group">
					    <label for="password" class="col-sm-2 control-label">Password</label>
					    <div class="col-sm-8">
					      <input type="password" name="password" class="form-control" id="password" placeholder="Password">
					    </div>
					  </div>
					 
					  <div class="form-group">
					    <div class="col-sm-offset-8 col-sm-4">
					      <button type="submit" class="btn btn-primary">Login</button>
					    </div>
					  </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>